# Generated by Django 3.1.7 on 2021-03-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0004_auto_20210302_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='producent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.producent'),
        ),
    ]
